# -*- coding: utf-8 -*-
"""AppUsedCarPriceModel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15O3ywr3EwU_mReiPI8R8CtbHmiKXcWmJ
"""

colimport pandas as pd
import numpy as np
df = pd.read_csv("/content/drive/MyDrive/UsedCarPriceModel/PakWheelsDataset.csv")
#df.value_counts()

"""#**To Make User Interface (UI) Using Gradio**`"""

!pip install nltk

!pip install gradio

# Load Dataset from my Google Drive
import pandas as pd
import numpy as np
import joblib
import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
nltk.download('punkt_tab')
stopwords.words('english')
import string
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
import gradio as gr

# load the model
model = joblib.load("/content/drive/MyDrive/UsedCarPriceModel/UsedCarPriceTrainedModel.joblib")
cv = joblib.load("/content/drive/MyDrive/UsedCarPriceModel/CounterVectorizer.joblib")
ohe = joblib.load("/content/drive/MyDrive/UsedCarPriceModel/OneHotEncoder.joblib",)
sc = joblib.load("/content/drive/MyDrive/UsedCarPriceModel/StandardScaller.joblib",)
print("1-model load successfully")

# make a function for care price prediction(in which pass the all input features)
def car_price_prediction_f(CompanyModel, Features, Province, Color, Body_Type,
                           Year, Millage, Engine_Capacity, Fuel, Transmission, Assembly):
    print(CompanyModel)
    print("2-input values pass to car price function successfully")

    # create Lists of input values
    text_col = [ 'CompanyModel', 'Features']
    int_col  = ['Year', 'Millage', 'Engine_Capacity']
    cat_col  = [ 'Fuel', 'Transmission', 'Province', 'Color', 'Assembly', 'Body_Type']

    # Ctreate DataFrames of input values for text input
    text_df = pd.DataFrame([{
                "CompanyModel"         :CompanyModel,
                "Features"             :Features,
                          }])
    print("3-make text_df" , text_df[text_col])

    # Ctreate DataFrames of input values for int type input
    int_df  = pd.DataFrame([{
                "Year"                 :Year,
                "Millage"              :Millage,
                "Engine_Capacity"      :Engine_Capacity
                          }])
    print("4-make int_df" , int_df[int_col])

    # Ctreate DataFrames of input values for categorical input
    cat_df  = pd.DataFrame([{
                "Fuel"                  :Fuel,
                "Transmission"          :Transmission,
                "Province"              :Province,
                "Color"                 :Color,
                "Assembly"              :Assembly,
                "Body_Type"             :Body_Type
                          }])
    print("5-make cat_df" , cat_df[cat_col])
    print("6-make 3 data frames for fetching  variable values successfully")

    # Create text processing function
    def text_processing_f(text):

        text = text.lower()   # text convert to lowercase
        text = nltk.word_tokenize(text)  # Tokenize the words
        text = [i for i in text if i.isalnum()] # Remove Special Characters
        text = [i for i in text
            if i not in stopwords.words('english') and
            i not in string.punctuation] # Remove stopwords loop
        text = [ps.stem(i) for i in text]  # Stemming (eg look,looked,looking convert to look)
        return " ".join(text)
    print("7-create text processing function successfully")

    # Apply text processing function on text_df
    text_df['CompanyModel'] = text_df['CompanyModel'].apply(text_processing_f)
    text_df['Features'] = text_df['Features'].apply(text_processing_f)

    print("8-text_df" , text_df[text_col])
    print("9-apply text processing function on text_df successfully")

    # Apply counter vectorizer on text_df
    cv_text = cv.transform(text_df['CompanyModel'] + " " + text_df['Features'])
    vectorized_text_df = pd.DataFrame(cv_text.toarray(),
                              columns=[f"text_{col}" for col in cv.get_feature_names_out()],
                              index=text_df.index)
    print("vectorized_text_df.shape : " , vectorized_text_df.shape)
    print("10-apply counter vectorizer on text_df successfully")

    # Apply Standard Scalling on int_df
    sc_int = sc.transform(int_df)
    scaled_int_df = pd.DataFrame(sc_int,
                                 columns=int_df.columns,
                                 index= int_df.index)
    print("scaled_int_df.shape : ", scaled_int_df.shape)
    print("11-apply Standard Scalling on int_df successfully")

    # Apply one hot encoder on cat_df
    ohe_cat = ohe.transform(cat_df)
    encoded_cat_df = pd.DataFrame(ohe_cat,
                                  columns=ohe.get_feature_names_out(cat_df.columns),
                                  index=cat_df.index)
    print("encoded_cat_df.shape : ", encoded_cat_df.shape)
    print("12-apply OneHotEncoder on cat_df successfully")

    # Combine Data Frames : text_df, int_df, cat_df
    final_combined_input_df = pd.concat([vectorized_text_df, scaled_int_df, encoded_cat_df], axis=1)
    print("final_combined_input_df.shape : ", final_combined_input_df.shape)
    print("13-combine Data Frames : text_df, int_df, cat_df successfully")

    # input features forced to become as model features
    final_combined_input_df = final_combined_input_df.reindex(columns=model.feature_names_in_, fill_value=0)
    print("forced final_combined_input_df.shape : ", final_combined_input_df.shape)
    print("14-input features forced to become as model features successfully")

    # Prediction
    prediction = model.predict(final_combined_input_df)
    print("15-make prediction successfully")

    return prediction[0]
    print("16-return prediction successfully")
    print("17-Wow! car_price_prediction_f run succesfully")

# make the Gradio Interface
iface = gr.Interface(
    fn = car_price_prediction_f,

    inputs=[
            gr.Textbox(lines=1,scale=2,    label="Company & Model Details"),
            gr.Textbox(lines=1,scale=2,    label="Features like Radio, Air Bags, Air Conditioning, CD Player etc"),
            gr.Textbox(lines=1,scale=2,    label="Province where Car Registered"),
            gr.Textbox(lines=1,scale=2,    label="Color"),
            gr.Textbox(lines=1,scale=2,    label="Body Type"),
            gr.Number(         scale=2,    label="Model Year"),
            gr.Number(         scale=2,    label="Millage(Km) to Run"),
            gr.Number(         scale=2,    label="Engine Capacity (cc)"),

            gr.Dropdown(choices=['Petrol', 'Hybrid', 'Diesel' , 'CNG' , 'Electric' , 'LPG'],
                          value='',
                          scale=3,
                          label= 'Fuel Type'),
            gr.Dropdown(choices=['Automatic' , 'Manual'],
                          value='',
                          scale=3,
                          label= 'Transmission Type'),
            gr.Dropdown(choices=['Local', 'Imported'],
                          value='',
                          scale=3,
                          label='Assembly Region')
            ],
    outputs= gr.Number(label='Predicted Car Price in Lac'),
    title = "Used Car price Prediction App",
    description = "Enter Car's Detail to Predict its Price"
    )
iface.launch(share=True,debug=True)