# -*- coding: utf-8 -*-
"""UsedCarPriceModel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIdcxV7aDLWzY2-DMvpUbO_mCdf0rSae

#**ML Model to Predict Price of Used car**

**Pakistan Used Cars Dataset**

This dataset contains information on 80,033 used cars listed on PakWheels.com, one of Pakistan's largest online car marketplaces. The data was scraped to provide insights into the Pakistani automotive market, including car models, pricing trends, and specifications.
https://www.kaggle.com/datasets/muhamedumarjamil/pakistan-used-cars-dataset

**Upload the Dataset**
"""

import pandas as pd
import numpy as np
df = pd.read_csv("/content/drive/MyDrive/UsedCarPriceModel/PakWheelsDataset.csv")
df.head(5)

"""##**1-Data Cleaning**"""

# print the column names
print(df.columns)

# Remove the spaces from column name
df.columns = df.columns.str.strip()

# Rename the coulmns
df.rename(columns={
    'nam':'Company&model',
    'Engine Capacity':'Engine_Capacity',
    'Body Type':'Body_Type',
    'Ad Reference':'Ad_Reference',
    'Owner nam':'Owner_Name'},
          inplace=True)
print(df.columns)

# Delete the unnecessary columns
df.drop(columns={'Ad_Reference','Owner_Name', 'url'},inplace=True)
print(df.columns)

# Checking How many rows and columns
df.shape

# checking - missing values in th dataset
df.isnull().sum()

# Delete the rows which have any missing values
df.dropna(axis=0, inplace=True)

# Checking for Duplicate values
df.duplicated().sum()

# Remove Duplicate values
df.drop_duplicates(keep='first',inplace=True)

# Again Checking Duplicate Values
df.duplicated().sum()

# Checking - How many rows have NaN value
df.isna().any(axis=0).sum()

# Checking - How many remaining no of rows and no of columns
df.shape

# Remove text from columns : 'Price' - 'Millage' - 'Engine_Capacity'
df['Price'] = df['Price'].str.replace(r'[^0-9.]' , '' , regex=True)
df['Millage'] = df['Millage'].str.replace(r'[^0-9.]' , '' , regex=True)
df['Engine_Capacity'] = df['Engine_Capacity'].str.replace(r'[^0-9.]' , '' , regex=True)
df.head(5)

df.info()

# find how many empty string in  columns
print((df['Price'] == '').sum())
print((df['Millage'] == '').sum())
print((df['Engine_Capacity'] == '').sum())

# delete the empty string in the Price column
df = df[df['Price'].str.strip() != '']

# now check empty string in Price column
print((df['Price'] == '').sum())

df.shape # reduce no of rows

df.head(3)

#convert object type columns into int type columns
df.iloc[:, 1] = df.iloc[:, 1].astype('float') # Column = Price
df.iloc[:, 2] = df.iloc[:, 2].astype('int64') # column = Year
df.iloc[:, 3] = df.iloc[:, 3].astype('int64') # column = Millage
df.iloc[:, 9] = df.iloc[:, 9].astype('float').astype('int64') # column = Engine_Capacity
df.info()

#convert object type columns into int type columns
df['Price'] = df['Price'].astype('float')
df['Millage'] = df['Millage'].astype('int64')
df['Engine_Capacity'] = df['Engine_Capacity'].astype('int64')
df.info()

"""##**Exploratory Data Analysis (EDA)**"""

df.head(3)

df['Fuel'].value_counts()

# draw a pie graph
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize = (8,5))
df['Fuel'].value_counts().plot(kind='bar')
plt.show()

"""**Observation : Petrol is by far the most common fuel type in the dataset, while LPG, Electric, Diesel, Hybrid, and CNG vehicles are present in much smaller numbers, indicating a highly imbalanced distribution.**"""

df['Transmission'].value_counts()

plt.figure (figsize = (5,5))
plt.pie(df['Transmission'].value_counts(),
                labels = (df['Transmission'].value_counts()).index,
                autopct = '%1.1f%%')
plt.show()

"""**observation : this pie chart illustrates the class distribution of a binary target variable, showing a slightly imbalanced dataset where Automatic represents 56.1% and Manual represents 43.9%.**"""

df['Assembly'].value_counts()

plt.figure (figsize=(5,5))
plt.pie(df['Assembly'].value_counts(),
            labels = (df['Assembly'].value_counts()).index,
            autopct = '%1.1f%%')
plt.show()

"""**Observation : this pie chart displays the categorical distribution of the feature, showing a majority share of Local at 67.1% compared to Imported at 32.9%.**"""

print("maximum value of Engine Capacity : " , df['Engine_Capacity'].max())
print("minimum value of Engine Capacity : " , df['Engine_Capacity'].min())
print("maximum value of Millage : " , df['Millage'].max())
print("minimum value of Millage : " , df['Millage'].min())

df.shape

# delete the rows which has its Engine_Capacty value less than 600
df = df[df['Engine_Capacity'] >= 600]

df.shape

df[['Price', 'Year', 'Millage', 'Engine_Capacity']].describe()

"""Oservation : The dataset contains 52,344 vehicle records spanning model years 1952 to 2025, with an average price of ~2.98M and average mileage near 99,375 miles.
Key Result: Significant right-skewness and extreme upper outliers are present across Price (up to 9.995M) and Millage (reaching 1.0M miles), where max values far exceed their respective 75th percentiles.

#**Data Processing**
"""

df.head(3)

"""###**Split the Dataset**"""



from sklearn.model_selection import train_test_split
X = df.drop(columns=['Price'])
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=50)
print(X_train.shape)
print(X_test.shape)

"""#**Data Processing of X_train & X_test**

##**Text Processing**
"""

X_train.columns

# Split X_train into 3 dataframes
X_train_text_df = X_train[['Company&model', 'Features']].copy()
X_train_int_df = X_train[['Year', 'Millage', 'Engine_Capacity']].copy()
X_train_cat_df = X_train[['Fuel', 'Transmission', 'Province', 'Color','Assembly', 'Body_Type']].copy()

X_test.columns

# Split X_test into 3 dataframes
X_test_text_df = X_test[['Company&model', 'Features']].copy()
X_test_int_df = X_test[['Year', 'Millage', 'Engine_Capacity']].copy()
X_test_cat_df = X_test[['Fuel', 'Transmission', 'Province', 'Color','Assembly', 'Body_Type']].copy()

!pip install nltk

"""**Make a function for text processing of X_train_text_df and X_test_text_df**"""

import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
nltk.download('punkt_tab')
stopwords.words('english')
import string
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def text_processing_f(text):
    # text convert to lowercase
    text = text.lower()

    # Tokenize the words
    text = nltk.word_tokenize(text)

    # Remove Special Characters
    text = [i for i in text if i.isalnum()]

    # Remove stopwords
    text = [i for i in text
            if i not in stopwords.words('english') and
            i not in string.punctuation]

    # Stemming (eg look,looked,looking convert to look)
    text = [ps.stem(i) for i in text]

    return " ".join(text)

"""**X_train >> Apply Text Processing Function on columns 'Company&Model' and 'Features'**"""

X_train_text_df.head(3)

X_train_text_df['Company&model'] = X_train_text_df['Company&model'].apply(text_processing_f)
X_train_text_df['Features'] = X_train_text_df['Features'].apply(text_processing_f)

X_train_text_df.head(3)

"""**X_train >> Apply Text Processing Function on columns 'Company&Model' and 'Features'**"""

X_test_text_df.head(3)

X_test_text_df['Company&model'] = X_test_text_df['Company&model'].apply(text_processing_f)
X_test_text_df['Features'] = X_test_text_df['Features'].apply(text_processing_f)

X_test_text_df.head(3)

"""****

##**Apply Vectorizer on Text Columns**

**X_train & X_test >> vectorize the text columns 'Company&Model' and 'Features'**
"""

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
cv = CountVectorizer()
tfidf = TfidfVectorizer()

# X_train >> vectorize the text column 'Company&Model'
cvc1 = cv.fit_transform(X_train_text_df['Company&model'])
# convert to DataFrame
cvc1_df = pd.DataFrame(cvc1.toarray(),
                      columns = [f"text_{col}" for col in cv.get_feature_names_out()],
                      index = X_train_text_df.index
                      )

# X_test >> vectorize the text column 'Company&Model'
cvc2 = cv.transform(X_test_text_df['Company&model'])
# convert to DataFrame
cvc2_df = pd.DataFrame(cvc2.toarray(),
                      columns = [f"text_{col}" for col in cv.get_feature_names_out()],
                      index = X_test_text_df.index
                      )

# X_train >> vectorize the text column 'Features'
cvf1 = cv.fit_transform(X_train_text_df['Features'])
# convert to DataFrame
cvf1_df = pd.DataFrame(cvf1.toarray(),
                      columns = [f"text_{col}" for col in cv.get_feature_names_out()],
                      index = X_train_text_df.index
                      )

# X_test >> vectorize the text column 'Features'
cvf2 = cv.fit_transform(X_test_text_df['Features'])
# convert to DataFrame
cvf2_df = pd.DataFrame(cvf2.toarray(),
                      columns = [f"text_{col}" for col in cv.get_feature_names_out()],
                      index = X_test_text_df.index
                      )

# X_train >> Combine vectorized text columns (Company&model and Features)
vec_X_train_text_df = pd.concat([cvc1_df, cvf1_df], axis=1)

# X_test >> Combine vectorized text columns (Company&model and Features)
vec_X_test_text_df = pd.concat([cvc2_df, cvf2_df], axis=1)

print("Shape of Vectorized vec_X_train_text_df :  " , vec_X_train_text_df.shape)
print("Shape of Vectorized vec_X_test_text_df  :  " , vec_X_test_text_df.shape)

"""##**Apply Scalling on the int Type Columns**

**X_train >> Scalling the  X_train_int_df by using standard scalling**
"""

from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

# Scalling of X_train
scaled_X_train_int = ss.fit_transform(X_train_int_df)
# convert into dataframe
scaled_X_train_int_df = pd.DataFrame(scaled_X_train_int,
                      columns = X_train_int_df.columns,
                      index = X_train_int_df.index
                      )
print(scaled_X_train_int_df)
print("Shape of scaled_X_train_int_df : ", scaled_X_train_int_df.shape)

"""**X_test >> Scalling the  X_test_int_df by using standard scalling**"""

scaled_X_test_int = ss.fit_transform(X_test_int_df)
# convert into dataframe
scaled_X_test_int_df = pd.DataFrame(scaled_X_test_int,
                      columns = X_test_int_df.columns,
                      index = X_test_int_df.index
                      )

print(scaled_X_test_int_df)
print("Shape of scaled_X_test_int_df : ", scaled_X_test_int_df.shape)

"""##**Apply Encoding**

**X_train & X_test >> Data processing of categorical columns by OneHotEncoder**
"""

X_train_cat_df.columns

X_test_cat_df.columns

import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
ohe= OneHotEncoder(sparse_output=False,
                    handle_unknown='ignore',
                    dtype=np.int64)

# X_train OneHotEncoding ----------------------------------------------------------
encoded_X_train_cat = ohe.fit_transform(X_train_cat_df)
# convert into dataframe
encoded_X_train_cat_df = pd.DataFrame(encoded_X_train_cat,
                      columns = ohe.get_feature_names_out(X_train_cat_df.columns),
                      index = X_train_cat_df.index
                      )
print("Shape of encoded encoded_X_train_cat_df : " , encoded_X_train_cat_df.shape)

# X_test OneHotEncoding ---------------------------------------------------------------
encoded_X_test_cat = ohe.transform(X_test_cat_df)
# convert into dataframe
encoded_X_test_cat_df = pd.DataFrame(encoded_X_test_cat,
                      columns = ohe.get_feature_names_out(X_test_cat_df.columns),
                      index = X_test_cat_df.index
                      )
print("Shape of encoded_X_test_cat_df  : " , encoded_X_test_cat_df.shape)

"""###**Join Dataframe of X_train_text_df , X_train_int_df , X_train_cat_df**"""

final_X_train = pd.concat([vec_X_train_text_df, scaled_X_train_int_df, encoded_X_train_cat_df], axis=1)
print(final_X_train.shape)

"""###**Join DataFrame of X_test_text_df , X_test_int_df , X_test_cat_df**"""

final_X_test = pd.concat([vec_X_test_text_df, scaled_X_test_int_df, encoded_X_test_cat_df], axis=1)
print(final_X_test.shape)

"""**Why use transform in X_test :**

1- Preventing the leakage of data                                           
 In Scaling >> fit_transform the recalculate the statistical rule like mean, standard deviation etc, and data artificialy normalized. Do not need it in X_train.                                                                     
In vectorizer >> fit_transform builds a new vocabulary. Do not need it in X_train.                                                                  
2- Insuring the allignment of features                                  
ML model trained on strick mathmatical formula. For prediction no of columns should be same in X_train and X_test                                       
Conclusion: when any feature or word do not in X_train, transform safely assign 0 across all correspoding columns or matrix                         
Important Note : When apply CounterVectorizer on X_train & X_test in the same cell , It make the same no of columns                                     
When apply OneHotEncoder on X_train & X_test in the same cell , It make the same no of columns

#**Train the Model**

**DecisionTreeRegressor**
"""

from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, mean_absolute_percentage_error

dtr = DecisionTreeRegressor(max_leaf_nodes=15,random_state=5)
dtr.fit(final_X_train, y_train)

# Predicting values on test set of data
dtr_predicted_values = dtr.predict(final_X_test)

y_test.shape

final_X_test.shape

dtr_predicted_values.shape

# Checking Model Errors
print("Mean Absolute Error            : " , mean_absolute_error(y_test, dtr_predicted_values))
print("Mean Squared_error             : " , mean_squared_error(y_test, dtr_predicted_values))
print("Root Mean Squared Error        : " , root_mean_squared_error(y_test, dtr_predicted_values))
print("Mean Absolute Percentage Error : " , mean_absolute_percentage_error(y_test, dtr_predicted_values))

"""**RandomForestRegressor**"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, mean_absolute_percentage_error

rfr = DecisionTreeRegressor(max_leaf_nodes=15,random_state=5)
rfr.fit(final_X_train, y_train)

rfr_predicted_values = rfr.predict(final_X_test)
print("Mean Absolute Error            : " , mean_absolute_error(y_test, rfr_predicted_values))
print("Mean Squared_error             : " , mean_squared_error(y_test, rfr_predicted_values))
print("Root Mean Squared Error        : " , root_mean_squared_error(y_test, rfr_predicted_values))
print("Mean Absolute Percentage Error : " , mean_absolute_percentage_error(y_test, rfr_predicted_values))

"""**CatBoostRegressor**"""

!pip install catboost

"""**Lasso Linear Model**"""

from sklearn.linear_model import Lasso, Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, mean_absolute_percentage_error

ls = Lasso(alpha=0.1)
ls.fit(final_X_train, y_train)

ls_predicted_values = ls.predict(final_X_test)
print("Mean Absolute Error            : " , mean_absolute_error(y_test, ls_predicted_values))
print("Mean Squared_error             : " , mean_squared_error(y_test, ls_predicted_values))
print("Root Mean Squared Error        : " , root_mean_squared_error(y_test, ls_predicted_values))
print("Mean Absolute Percentage Error : " , mean_absolute_percentage_error(y_test, ls_predicted_values))

"""**Ridge Linear Model**"""

ri = Ridge(alpha=0.1)
ri.fit(final_X_train, y_train)

ri_predicted_values = ri.predict(final_X_test)
print("Mean Absolute Error            : " , mean_absolute_error(y_test, ri_predicted_values))
print("Mean Squared_error             : " , mean_squared_error(y_test, ri_predicted_values))
print("Root Mean Squared Error        : " , root_mean_squared_error(y_test, ri_predicted_values))
print("Mean Absolute Percentage Error : " , mean_absolute_percentage_error(y_test, ri_predicted_values))

"""###**I selecet Ridge Regression its regularization smoothly handles over highly correlated features without overfitting. It reducing pricing error to just 4.67Lac percentage error reducing to 79%**"""

import joblib
joblib.dump(ri, open('/content/drive/MyDrive/UsedCarPriceModel/UsedCarPriceTrainedModel.joblib', 'wb'))
joblib.dump(ss, open('/content/drive/MyDrive/UsedCarPriceModel/StandardScaller.joblib', 'wb'))
joblib.dump(ohe, open('/content/drive/MyDrive/UsedCarPriceModel/OneHotEncoder.joblib', 'wb'))
joblib.dump(cv, open('/content/drive/MyDrive/UsedCarPriceModel/CounterVectorizer.joblib', 'wb'))